parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        driver:   pdo_mysql
        server_version: 5.6
        url: "%env(DATABASE_URL)%"
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
            engine: InnoDB
        types:
            datetime_microsecond:
                class: App\Data\Database\Types\DateTimeMicrosecondType
            enum_effects:
                class: App\Data\Database\Types\EnumEffectsType
            enum_effect_display_group:
                class: App\Data\Database\Types\EnumEffectsDisplayGroupType
        mapping_types:
            enum: string

    orm:
        auto_generate_proxy_classes: false
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                dir:  "%kernel.project_dir%/src/Data/Database/Entity"
                is_bundle: false
                type: annotation
                prefix: App\Data\Database\Entity
        filters:
          deleted_items_filter:
            class: App\Data\Database\Filters\DeletedItemsFilter
            enabled: true
