parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        driver:   pdo_pgsql
        server_version: 9.8
        host:     "%env(DB_WRITE_HOST)%"
        port:     "%env(DB_PORT)%"
        dbname:   "%env(DB_NAME)%"
        user:     "%env(DB_WRITE_USER)%"
        password: "%env(DB_WRITE_PASSWORD)%"
        slaves:
            slave1:
                host:     "%env(DB_READ_HOST)%"
                port:     "%env(DB_PORT)%"
                dbname:   "%env(DB_NAME)%"
                user:     "%env(DB_READ_USER)%"
                password: "%env(DB_READ_PASSWORD)%"


    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                dir:  "%kernel.project_dir%/src/Data/Database/Entity"
                is_bundle: false
                type: annotation
                prefix: App\Data\Database\Entity
