monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: ERROR
            passthru_level: NOTICE
            handler:      nested
        nested:
            type:  error_log
            level: debug
        console:
            type:  console
