monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: ERROR
            passthru_level: NOTICE
            handler: nested
        nested:
            type:  stream
            path:  "php://stdout"
            level: debug
        console:
            type:  console
