version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/api.www.planetcargo.live/
permissions:
  - object: /
    owner: nginx
    group: nginx
hooks:
  AfterInstall:
    - location: scripts/fetch-parameters.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/application-start.sh
      timeout: 300
