version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/api.www.planetcargo.live/
permissions:
  - object: /
    owner: nginx
    group: nginx

hooks:
  AfterInstall:
    - location: bin/fetch-parameters.sh
      timeout: 300
  ApplicationStart:
    - location: bin/application-start.sh
      timeout: 300
