# docker-compose file for local dev only
version: "3"


services:
  cargo-api-php:
    image: planet-cargo-api:latest
#    image: 226925275209.dkr.ecr.us-east-1.amazonaws.com/planet-cargo-api:latest
    links:
      - cargo-db
    volumes:
      - .:/var/www
    working_dir: /var/www
    environment:
      APP_ENV: "dev"

  cargo-api-nginx:
    image: nginx:latest
    links:
      - cargo-api-php
    ports:
      - 8080:80
    volumes:
      - .:/var/www
      - ./nginx:/etc/nginx/conf.d

  cargo-db:
    restart: always
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: "root"
      POSTGRES_USER: "root"
      POSTGRES_DB: "cargo"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgres

volumes:
  postgres-data:


