# docker-compose file for local dev only
version: "3"

services:
  cargo-api-php:
    image: planet-cargo-base-php:latest
    volumes:
      - .:/var/www
    working_dir: /var/www
    environment:
      APP_ENV: "dev"

  cargo-api-nginx:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - .:/var/www
      - ./conf/docker-nginx:/etc/nginx/conf.d

  cargo-db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:


