imports:
    - { resource: services.yml }

parameters:
    hostname: https://www.planetcargo.live
    distance_multiplier: 3600

framework:
    secret: 'ToDOSetARealSecret'
    router:
        resource: '%kernel.project_dir%/config/routing.php'
        strict_requirements: true

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%env(DB_WRITE_HOST)%"
        port:     "%env(DB_PORT)%"
        dbname:   "%env(DB_NAME)%"
        user:     "%env(DB_WRITE_USER)%"
        password: "%env(DB_WRITE_PASSWORD)%"
        slaves:
            slave1:
                host:     "%env(DB_READ_HOST)%"
                port:     "%env(DB_PORT)%"
                dbname:   "%env(DB_NAME)%"
                user:     "%env(DB_READ_USER)%"
                password: "%env(DB_READ_PASSWORD)%"
        charset:  UTF8MB4
        types:
            uuid_binary:
                class: Ramsey\Uuid\Doctrine\UuidBinaryType
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        mappings:
            App:
                dir:  "%kernel.root_dir%/../src/Data/Database/Entity"
                is_bundle: false
                type: annotation
                prefix: App\Data\Database\Entity

# Doctrine migrations
doctrine_migrations:
    dir_name: "%kernel.root_dir%/../src/Data/Database/Migration"
    namespace: App\Data\Database\Migration
    table_name: migration_versions
    name: Application Migrations

doctrine_cache:
    providers:
        data_cache:
            type: php_file

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: ERROR
            passthru_level: NOTICE
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console