services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    App\:
        resource: '../../src/*'
        exclude: '../../src/Data/Database/Entity/*'
        exclude: '../../src/Domain/*'

    App\Config\ApplicationConfig:
        arguments:
            - '%hostname%'
            - '%distance_multiplier%'

    App\Config\TokenConfig:
        arguments:
            - '%env(TOKEN_PRIVATE_KEY)%'
            - '%env(TOKEN_COOKIE_NAME)%'
            - '%env(TOKEN_ISSUER)%'
            - '%env(TOKEN_AUDIENCE)%'
            - '%env(TOKEN_ID)%'

    App\Controller\:
        resource: '../../src/Controller/'
        public: true
        tags: ['controller.service_arguments']

    Google_Client:
        class: Google_Client
        arguments:
            - client_id: '%env(OAUTH_GOOGLE_CLIENT_ID)%'
              client_secret: '%env(OAUTH_GOOGLE_CLIENT_SECRET)%'
