services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    # Register the service as an event listener
    App\FlashDataListener:
        tags:
            - { name: 'kernel.event_subscriber' }

    App\:
        resource: '../../src/*'
        exclude: '../../src/Data/Database/Entity/*'
        exclude: '../../src/Domain/*'

    App\Config\ApplicationConfig:
        arguments:
            - '%hostname_api%'
            - '%hostname_web%'
            - '%cookie_scope%'
            - '%distance_multiplier%'
            - "%env(MAILER_FROM_NAME)%"
            - "%env(MAILER_FROM_ADDRESS)%"

    App\Config\TokenConfig:
        arguments:
            - '%env(TOKEN_PRIVATE_KEY)%'
            - '%env(TOKEN_ISSUER)%'
            - '%cookie_scope%'

    App\Controller\:
        resource: '../../src/Controller/'
        public: true
        tags: ['controller.service_arguments']

    Google_Client:
        class: Google_Client
        arguments:
            - client_id: '%env(OAUTH_GOOGLE_CLIENT_ID)%'
              client_secret: '%env(OAUTH_GOOGLE_CLIENT_SECRET)%'

    Facebook\Facebook:
        class: Facebook\Facebook
        arguments:
            - app_id: '%env(OAUTH_FACEBOOK_APP_ID)%'
              app_secret: '%env(OAUTH_FACEBOOK_APP_SECRET)%'
              persistent_data_handler: '@App\Data\Oauth\Facebook\PersistentData'
              http_client_handler: '@App\Data\Oauth\Facebook\HttpClient'

    Abraham\TwitterOAuth\TwitterOAuth:
        class: Abraham\TwitterOAuth\TwitterOAuth
        arguments:
            - '%env(OAUTH_TWITTER_API_KEY)%'
            - '%env(OAUTH_TWITTER_API_SECRET)%'

    Stevenmaguire\OAuth2\Client\Provider\Microsoft:
        class: Stevenmaguire\OAuth2\Client\Provider\Microsoft
        arguments:
            - clientId: '%env(OAUTH_MICROSOFT_APP_ID)%'
              clientSecret: '%env(OAUTH_MICROSOFT_APP_SECRET)%'
              redirectUri: '%env(OAUTH_MICROSOFT_APP_REDIRECT)%'

    GuzzleHttp\Client:
        class: GuzzleHttp\Client

    DateTimeZone:
        class: DateTimeZone
        arguments:
            - 'UTC' # Always UTC. Only do conversion at the very edge with the user

    # Ensure that injected times are all the same instance
    DateTimeImmutable:
        class: DateTimeImmutable
        arguments:
            - "now"
            - '@DateTimeZone'

    Psr\SimpleCache\CacheInterface:
        class: Roave\DoctrineSimpleCache\SimpleCacheAdapter
        arguments:
            - "@doctrine_cache.providers.data_cache"
