services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    App\:
        resource: '../../src/*'
        exclude: '../../src/Data/Database/Entity/*'
        exclude: '../../src/Domain/*'

    App\Controller\:
        resource: '../../src/Controller/'
        public: true
        tags: ['controller.service_arguments']
