AWSTemplateFormatVersion: 2010-09-09
Description: >
  Setup the API cluster and services

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - alpha
      - beta
      - prod
    Default: prod

  ClusterNamePrefix:
    Type: String
    Default: cargo-api

  TasksStack:
    Type: String

  SecurityGroups:
    Type: List<AWS::EC2::SecurityGroup::Id>

  Subnets:
    Type: List<AWS::EC2::Subnet::Id>

Resources:
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub ${ClusterNamePrefix}-${Environment}

  APIService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref Cluster
      ServiceName: api
      LaunchType: 'FARGATE'
      DesiredCount: 0
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 0
      TaskDefinition:
        Fn::ImportValue: !Sub "${TasksStack}::APITask"
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups: !Ref SecurityGroups
          Subnets: !Ref Subnets

  ArrivalsService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref Cluster
      ServiceName: arrivals
      LaunchType: 'FARGATE'
      DesiredCount: 0
      DeploymentConfiguration:
        MaximumPercent: 100
        MinimumHealthyPercent: 0
      TaskDefinition:
        Fn::ImportValue: !Sub "${TasksStack}::ArrivalsTask"
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups: !Ref SecurityGroups
          Subnets: !Ref Subnets

    # todo - scheduled tasks for cleaner and timed

Outputs:
  ClusterName:
    Value: !Ref Cluster
    Export:
      Name: !Sub ${AWS::StackName}::ClusterName

