imports:
    - { resource: services.yml }

parameters:
    hostname_api: https://api.www.planetcargo.live
    hostname_web: https://www.planetcargo.live
    cookie_scope: .www.planetcargo.live
    distance_multiplier: 3600

framework:
    secret: 'ToDOSetARealSecret'
    router:
        resource: "%kernel.project_dir%/app/config/routing.php"
        strict_requirements: true

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        server_version: 5.6
        host:     "%env(DB_WRITE_HOST)%"
        port:     "%env(DB_PORT)%"
        dbname:   "%env(DB_NAME)%"
        user:     "%env(DB_WRITE_USER)%"
        password: "%env(DB_WRITE_PASSWORD)%"
        slaves:
            slave1:
                host:     "%env(DB_READ_HOST)%"
                port:     "%env(DB_PORT)%"
                dbname:   "%env(DB_NAME)%"
                user:     "%env(DB_READ_USER)%"
                password: "%env(DB_READ_PASSWORD)%"
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
            engine: InnoDB
        types:
            uuid_binary:
                class: Ramsey\Uuid\Doctrine\UuidBinaryType
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        mappings:
            App:
                dir:  "%kernel.root_dir%/../src/Data/Database/Entity"
                is_bundle: false
                type: annotation
                prefix: App\Data\Database\Entity

# Doctrine migrations
doctrine_migrations:
    dir_name: "%kernel.root_dir%/../src/Data/Database/Migration"
    namespace: App\Data\Database\Migration
    table_name: migration_versions
    name: Application Migrations

doctrine_cache:
    providers:
        data_cache:
            type: php_file

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: ERROR
            passthru_level: NOTICE
            handler:      nested
        nested:
            type:  error_log
            level: debug
        console:
            type:  console

swiftmailer:
    transport: "smtp"
    host:      "%env(MAILER_HOST)%"
    username:  "%env(MAILER_USERNAME)%"
    password:  "%env(MAILER_PASSWORD)%"
    spool:
        type: memory
    port: 587
    encryption: "tls"
    auth_mode: "login"
